######################################################################
##
## Filename: master1_test.udo
## Created on: Sun Apr 09 2:28:52 PM India Standard Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
